import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, RecaptchaVerifier, signInWithPhoneNumber, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
const cfg=window.CROPULSE_FIREBASE_CONFIG||{}; const configured=cfg.apiKey && !String(cfg.apiKey).includes('REPLACE_ME');
const msg=document.getElementById('authMessage'); const setMsg=(t,type='')=>{msg.textContent=t;msg.className='auth-message '+type};
if(!configured){setMsg('Firebase is not connected yet. Add your Firebase Web App config in firebase-config.js.','error');document.getElementById('googleBtn').disabled=true;document.getElementById('sendOtpBtn').disabled=true;}else{
 const app=initializeApp(cfg), auth=getAuth(app); const provider=new GoogleAuthProvider(); provider.setCustomParameters({prompt:'select_account'});
 onAuthStateChanged(auth,u=>{if(u && sessionStorage.getItem('croppulse_auth_redirect')==='1'){sessionStorage.removeItem('croppulse_auth_redirect');location.href='dashboard.html';}});
 document.getElementById('googleBtn').onclick=async()=>{try{setMsg('Opening Google sign-in…');const r=await signInWithPopup(auth,provider);localStorage.setItem('croppulse_user',JSON.stringify({name:r.user.displayName,email:r.user.email,photo:r.user.photoURL,phone:r.user.phoneNumber}));location.href='dashboard.html';}catch(e){setMsg(readable(e),'error')}};
 let verifier=null,confirmation=null;
 document.getElementById('sendOtpBtn').onclick=async()=>{const raw=document.getElementById('phone').value.replace(/\D/g,'');const cc=document.getElementById('countryCode').value;if(raw.length<7){setMsg('Enter a valid mobile number.','error');return;}try{setMsg('Sending OTP…');if(verifier) verifier.clear();verifier=new RecaptchaVerifier(auth,'recaptcha-container',{size:'invisible'});confirmation=await signInWithPhoneNumber(auth,cc+raw,verifier);document.getElementById('phoneBox').classList.add('hidden');document.getElementById('otpBox').classList.remove('hidden');setMsg('OTP sent. Enter the 6-digit code.','success');}catch(e){setMsg(readable(e),'error');verifier?.clear();verifier=null;}};
 document.getElementById('verifyOtpBtn').onclick=async()=>{const code=document.getElementById('otp').value.trim();if(code.length!==6){setMsg('Enter the 6-digit OTP.','error');return;}try{setMsg('Verifying…');const r=await confirmation.confirm(code);localStorage.setItem('croppulse_user',JSON.stringify({name:r.user.displayName||'Farmer',email:r.user.email,photo:r.user.photoURL,phone:r.user.phoneNumber}));location.href='dashboard.html';}catch(e){setMsg(readable(e),'error')}};
 document.getElementById('changeNumberBtn').onclick=()=>{document.getElementById('otpBox').classList.add('hidden');document.getElementById('phoneBox').classList.remove('hidden');document.getElementById('otp').value='';setMsg('');};
}
function readable(e){const c=e?.code||'';if(c.includes('unauthorized-domain'))return 'This domain is not authorized in Firebase Authentication.';if(c.includes('invalid-phone-number'))return 'The phone number format is invalid.';if(c.includes('too-many-requests'))return 'Too many attempts. Please try again later.';if(c.includes('invalid-verification-code'))return 'Incorrect OTP. Please check the code and try again.';if(c.includes('popup-closed-by-user'))return 'Google sign-in was closed before completion.';return e?.message?.replace(/^Firebase:\s*/,'')||'Authentication failed.'}
